### ISSUE TITLE
로그인 페이지

### ISSUE THREAD

**Issue by new-h2** [udemy-final-team2/Book-Hub-Project#34]
[FE]
- [ ] 소셜 로그인 버튼을 원에서 직사각형으로 변경한다.
- [ ] 소셜 로그인 화면을 별도의 컨테이너로 css를 구성해 두개의 컨테이너를 display: flex; flex-direction:row; 로 구성한다.
- [ ] 로그인에 성공했을 경우 문서 리스트로 이동한다.
- [ ] “다른 이메일로 로그인하기”를 “간편 로그인”으로 변경

[BE]
- [x] 프론트에서 입력된 값을 DB에 있는 값과 비교해 가입여부를 프론트에 보내준다.
- [ ] Spring Security 설정을 통해, 로그인된 유저에게 인증, 인가를 설정해준다.

**Comment by Jimoou** [comment]
세번째 스프린트 계획 결과 이 이슈는 JWT 발급 로직을 구현하여 다시 전담하기로 했고, 이슈를 정리해서 다시 생성하기로 하여 이슈 종료합니다.
