### ISSUE TITLE
02/24(금) 오후 4시 데모데이 준비

### ISSUE THREAD

**Issue by Jimoou** [udemy-final-team2/Book-Hub-Project#71]
02/24(금) 오후 4시에 있을 데모데이를 준비합니다. 간단한 ppt, 클래스 다이어그램, 발표내용을 협의합니다.

발표시간은 20~30분으로 가정합니다.
처음 5~10분은 협업에 관한 내용으로 주를 이룹니다.
이후 개인발표를 통해 각자가 구현한 기능을 각 5분정도의 시간으로 설명합니다.

* [x] 각자의 로직 설명할 수 있는 다이어그램 그리기
* [x] 다이어그램을 그리고 김지운에게 전달하기
* [x] 머지된 PR 하나 골라서 길이감 있게 수정하기
* [x] 수정된 PR을 스샷 찍어 김지운에게 전달하기
* [x] 각자가 그린 다이어그램을 중심으로 로직을 설명하는 연습하기

발표자
* [x] PPT 작성하기
* [x] 협업에 관한 내용 삽입하기
     * [x] 깃허브 이슈, PR 이미지 넣기
     * [x] 2주차 스프린트 회고를 기반으로 스토리 빌드업하기
           - 잘 안되었다고 생각하는 점과 개선하기 위해 선택한 방법 (진행속도가 느려진점)
* [x] 개인 발표 내용 삽입하기
     * [x] 로직 설명 다이어그램 이미지 넣기
     * [x] 관련 코드의 일부 보여주기

**Comment by Jimoou** [comment]
모두 고생하셨습니다~!

**Comment by alweiis** [comment]
데모데이 준비 고생하셨습니다! 남은 기간 잘 마무리해봐요!

**Comment by new-h2** [comment]
고생하셨습니다~ 저희조 잘 마무리할수있게 마지막까지 더 힘내겠습니다~
