### ISSUE TITLE
OAuth2 리다이렉트 issue

### ISSUE THREAD

**Issue by Jimoou** [udemy-final-team2/Book-Hub-Project#76]
유저가 로그인 성공시 유저의 entity를 가지고 토큰이 정상발급이 됩니다. DB에 값도 저장이 됩니다. 하지만, 리다이렉트 문제로 인해, 사이트 이동이 정상적으로 이동되는 것처럼 보이지 않으며, 원인을 아직 알 수 없는 mybatis 쿼리 오류로 `insertUser`함수가 `UserDTO`를 반환하지 않는 오류가 계속 생깁니다. 이또한, 사이트 이동에 어려움을 겪고 있습니다.

**Comment by alweiis** [comment]
고생하셨습니다~! 내일 테스트 종류하고 같이 문제를 해결해봅시다.

**Comment by Jimoou** [comment]
#78 다시 롤백하기로 했습니다. 이슈 종료합니다.
