### ISSUE TITLE
프로젝트를 JWT 기능 구현 전으로 롤백한다.

### ISSUE THREAD

**Issue by Jimoou** [udemy-final-team2/Book-Hub-Project#78]
JWT 필터를 사용하여 유저의 접근 권한을 제어하고, 유저의 정보를 추출하는 기능을 구현했다. 하지만, 현재 세션 방식으로 구현된 현재 프로젝트를 리팩토링하기엔 시간적으로 무리라고 판단하였고, 세션방식의 보안 안정성을 인정하기로 합의하였다.

**Comment by alweiis** [comment]
확인 완료하였습니다! 이후 스프린트 일정은 멘토님에게 통해 조언받은 내용을 기반으로 함께 진행해보아요!
